<?php

    function cards_menu()
    {
        $items = array();
        $items['cards/max'] = array(
            'title' => 'Max',
            'page callback' => 'cards_max',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['cards/diane'] = array(
            'title' => 'Diane',
            'page callback' => 'cards_diane',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['cards/santa'] = array(
            'title' => 'Santa',
            'page callback' => 'cards_santa',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        return $items;
    }

    function cards_max() {
        return 'To Valhallahhhh';
    }
    function cards_diane() {
        return 'You are Epicodawesome';
    }
    function cards_santa() {
        return 'Feliz Navidad';
    }
